### ISSUE TITLE
Criar testes para JobPostForm

### ISSUE THREAD

**Issue by PedroMarianoAlmeida** [PedroMarianoAlmeida/baby-dev-open-source#22]
Tem só um teste e que está falhando o **organism > JobPostForm**

**Comment by tarcisioandrade** [comment]
pull request enviado!

**Comment by PedroMarianoAlmeida** [comment]
Implementado em https://github.com/PedroMarianoAlmeida/baby-dev-open-source/pull/45... ficou TOPZERA!
