### ISSUE TITLE
Testar o "fechar container" no BottomContainer - onMouseLeave

### ISSUE THREAD

**Issue by PedroMarianoAlmeida** [PedroMarianoAlmeida/baby-dev-open-source#5]
No teste do componente **organism > UserStackSelector > BottomContainer** testar a funcionalidade de fechar o componente ao entrar com o mouse dele, sair com o mouse dele e ficar fora um tempo

Se der pode testar o debounced, de sair rapidinho e ele continuar aberto.

Eu não sei fazer esse movimentos de mouse com o Jest

Não se esqueça de ver o [Guia do Código](https://github.com/PedroMarianoAlmeida/baby-dev-open-source/blob/main/Guia%20do%20Código.md)

**Comment by RobsonTrasel** [comment]
Começando contribuição...

**Comment by PedroMarianoAlmeida** [comment]
Feito! Muito obrigado =D
