### ISSUE TITLE
Consertar o teste que verifica a propriedade de um componente em organisms > UserStackSelector > BottomContainer

### ISSUE THREAD

**Issue by PedroAlmeidaFetchly** [PedroMarianoAlmeida/baby-dev-open-source#6]
O teste **isSelected property is assign correctly** está lá escrito mas não funciona (por isso está "pulado").

Então se souber Jest e quiser colaborar será super bem vindo!

Não se esqueça de ver o [Guia do Código](https://github.com/PedroMarianoAlmeida/baby-dev-open-source/blob/main/Guia%20do%20Código.md)

**Comment by tarcisioandrade** [comment]
Creio que conseguir resolver, pull request enviado.

**Comment by PedroMarianoAlmeida** [comment]
Implementado por @tarcisioandrade no https://github.com/PedroMarianoAlmeida/baby-dev-open-source/pull/42

Muito bom o teste, verificando quanto TEM e quando NÃO TEM.
