### ISSUE TITLE
Refatorar/reorganizar estrutura de arquivos de organisms > UserStackSelector

### ISSUE THREAD

**Issue by PedroMarianoAlmeida** [PedroMarianoAlmeida/baby-dev-open-source#8]
Essa pasta não está seguindo a estrutura correta segundo o [Guia do Código](https://github.com/PedroMarianoAlmeida/baby-dev-open-source/blob/main/Guia%20do%20C%C3%B3digo.md), e também dá pra aproveitar e organizar os arquivos extras que estão "bagunçados".

Então o passo a passo é (**cada etapa em um commit**):

- Criar arquivo chamado **UserStackSelector** e passar tudo que está no **index** pra lá
- Deixar o arquivo **index** com o import default pra esse arquivo gerado (ver o Guia do Código, lá tem o padrão)
- Criar uma pasta chamada BottomContaner
- Colocar os arquivos relacionados ao BottomContainer lá 
- Resolver todos os imports pra não quebrar (não esqueça de rodar os testes e ver no Storybook se está certinho)
- Repetir o processo para o TopContainer

Atividade extra: Em cada uma dessas pastas criar um novo module.css e pegar as classes que são usadas apenas no respectivo (top ou bottom) - Deixando o **UserStackSelector** com menos classes

**Comment by tarcisioandrade** [comment]
Pull Request Enviado!
