### ISSUE TITLE
Refatorar props de organisms > UserStackSelector > TopContainer

### ISSUE THREAD

**Issue by PedroMarianoAlmeida** [PedroMarianoAlmeida/baby-dev-open-source#9]
Nesse componente está sendo enviado as props **showOptions** e **setShowOptions** apenas para fazer o toggle (trocar de verdadeiro pra falso) direto no onClick

Então gostaria de trocar com a seguinte abordagem (**cada etapa em um commit**):

- No componente pai (UserStackSelector) criar uma função chamada toggleShowOptions, que realiza essa tarefa
- Passar essa função como prop
- Substituir ali no onClick
- Nas props e na interface, remover o **showOptions** e **setShowOptions** e inserir o **toggleShowOptions**

Tarefa opcional: Refatorar também os testes, pois lá é passado o componente com suas props, então se elas mudaram tem que mudar lá também (os testes em si não precisa mexer) - Se precisar de ajuda me chama nessa parte

Não se esqueça de ver o [Guia do Código](https://github.com/PedroMarianoAlmeida/baby-dev-open-source/blob/main/Guia%20do%20C%C3%B3digo.md)

**Comment by tarcisioandrade** [comment]
Pull Request enviado!

**Comment by PedroMarianoAlmeida** [comment]
Implementado COM PERFEIÇÃO em https://github.com/PedroMarianoAlmeida/baby-dev-open-source/pull/43
